# Generated by Django 6.0 on 2026-04-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('pharmacist', 'Pharmacist')], max_length=20, null=True),
        ),
    ]
